services:
  config-server:
    image: maven:3.9.14-eclipse-temurin-17
    container_name: config-server
    working_dir: /workspace
    command: mvn spring-boot:run -Dspring-boot.run.profiles=native
    ports:
      - "8888:8888"
    environment:
      SERVER_PORT: 8888
      SPRING_PROFILES_ACTIVE: native
    volumes:
      - ./:/workspace
      - m2-cache:/root/.m2
    restart: unless-stopped

volumes:
  m2-cache:
