server:
  port: 8761

spring:
  security:
    user:
      name: admin
      password: admin123

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

# Info endpoint
info:
  app:
    name: Eureka Discovery Server
    description: Ticketti Service Registry
    version: 1.0.0
